berp enclosing_try.py
<<<
>>>
caught exception
after handler
12
>>>2
>>>=0
